### ISSUE TITLE
Notebook klasörü 

### ISSUE THREAD

**Issue by caglarmert** [ucrayca/Aycaucr#1]
Issuelar reponun eksikliklerinin veya iyileştirme önerilerinin yazıldığı yerler. Buraya herkes bir issue açabilir. reponun sahibi bu issueların önemine göre işleme alır ve yavaş yavaş kapatırlar. 

Örnek olarak şu anda bu repoya bir tane daha klasör açılması isteği var. Reponun sahibi bunu kabul edip klasörü açabilir. Klasörü açtıktan sonra buraya tekrar gelip issueya yorumunu yazarsın (örneğin: klasör açıldı) ve commentin solundaki close issue seçerek kapatırsın.

.ipynb dosyalarının bir arada durabileceği notebook klasörünün açılması gerekiyor

**Comment by ucrayca** [comment]
klasör açıldı
