### ISSUE TITLE
NASA Engine Degradation Datasetinin incelenmesi

### ISSUE THREAD

**Issue by caglarmert** [ucrayca/Aycaucr#2]
- [x] NASA Engine [Degradation Datasetinin](https://ti.arc.nasa.gov/c/6/) incelenmesi. 
- [x] İlgili dataset hakkındaki [çalışmanın ](https://github.com/ucrayca/Aycaucr/blob/master/notebook/NASA_RUL_Estimation.ipynb) incelenmesi.

**Comment by ucrayca** [comment]
Dataseti incelendi. Eror olan kod yüklenecek ve error lerin analizi yapılacaktı.

**Comment by ucrayca** [comment]
Sensörler; sıcaklık ,hız basınç gibi şeyleri tutar. SORU: Bu verileri kullanarak remaining useful life hesaplanabilir mi? C-MAPSS trainve test  dataları sağlaması için kullanılmakta. Missing value, outlier bakılmakta. std hesaplamasının olduğu bir tablo elde edilerek std=0 sıfır olanları tablodan çıkardı. Çünkü std =0 demek arızalı olduğu anlamına gelmekte. Bunlar dışında scale işlemleri ttf hesabı gibi şeyleri yapmış ve son olarak KERAS kullanarak bir neural network modeli oluşturmuş ve çıkan  1 output regression problemi ndeniyle rul tahmininde kullanılır.Gerçek ve tahminler karşılaştırılır ve MSE hesabı yapılmış son olarak.

**Comment by ucrayca** [comment]
İçerik dışında bazı kullanılan kalıplara da baktım.
kolon adı verme 
ilk 5 satırı basma ya da describe işlemi 
dosyayı include etme vs
inceledim biraz aklımda kalan bir şeyler var hepsi olmasa da
