### ISSUE TITLE
Yapay Zeka Sunumu

### ISSUE THREAD

**Issue by caglarmert** [ucrayca/Aycaucr#3]
(Perşembe günü yapılan sunum)
Adımlar:
- [x] Sunumun Hazırlanması
- [x] Sunum Yapılması
- [x] Sunumun Githubda ilgili klasöre yüklenmesi
- [x] Geri bildirimlerin verilmesi
- [x] Geri bildirimler ışığında sunum versiyon 2 oluşturulması

**Comment by ucrayca** [comment]
@caglarmert  geri bildirim bekleniyor.

**Comment by caglarmert** [comment]
> @caglarmert geri bildirim bekleniyor.

- Görseller çok güzel ve dikkat çekici.
- Sunum renkleri güzel seçilmiş.
- İngilizce yazılar ve terimler olması doğru, bu terimlerin Türkçeleri genelgeçer bilinir değiller.
- Uzun cümlelerin yerine kısa anahtar kelimeler kullanılabilir.
- Bir slaytta en fazla 4-5 bulletpoint.
- Her satırda en fazla 5-6 kelime.

**Comment by ucrayca** [comment]
Sunum versiyon 2 oluşturuldu ve sunum klasörüne yüklendi. Mümkün olan yerlerde kısaltmaları yaptım 7-8 tane bulletpoint yerine daha az sayıda kullanmaya çalıştım uzun açıklamalar yerine de daha kısa,hatırlatmak amaçlı, ifadeleri kullanmaya çalıştım. (Bazı yerler belki hala uzun olabilir )

**Comment by caglarmert** [comment]
Elina sağlık, 2. versiyonun bütünlüğü güzel görünüyor.
