### ISSUE TITLE
Systematic Literature Review (SLR)

### ISSUE THREAD

**Issue by caglarmert** [ucrayca/Aycaucr#4]
Systematic Literature Review (SLR)
Keywords:
- Remaining Useful Lifetime Estimation
- Data Augmentation AND Time Series
Databases:
- https://scholar.google.com (easy and largest DB)
Requirements:
1. Read abstracts of papers found, decide whether they are appropriate to our topic
2. At least 5 papers for RUL estimation
3. At least 5 papers for data augmentation in time series
4. Store relevant papers into references folder

**Comment by ucrayca** [comment]
refereranslar dosyasına 5 RUL estimation ve 5 tane data augmentation makalesi yüklendi.
