### ISSUE TITLE
Yazılım Geliştirme Ortamının Kurulması

### ISSUE THREAD

**Issue by caglarmert** [ucrayca/Aycaucr#5]
Yazılım geliştirme ortamı için lokal bilgisayara:
- [x] python (3.7.5 64bit) (Anaconda olmasın)
- [x] pycharm (community edition)
- [x] jupyter lab (windows cmd ekranından: pip install jupyterlab)
kurulması

**Comment by ucrayca** [comment]
@caglarmert aslında hepsi var ama anaconda ile beraber kurmustum

**Comment by ucrayca** [comment]
hepsi kuruldu
