### ISSUE TITLE
Introduction to Machine Learning Algorithms

### ISSUE THREAD

**Issue by caglarmert** [ucrayca/Aycaucr#9]
- [x] Clustering
- [x] Classification

Yöntemleri için kullanılan algoritmaların tek cümlelik özetleri hazırlanacak.

**Comment by ucrayca** [comment]
CLUSTERING

- Unsupervised learning method
- The task of dividing the population or data points into a number of groups such that data points in the same groups are more similar to other data points in the same group than those in other groups. In simple words, the aim is to segregate groups with similar traits and assign them into clusters.
- Clustering is very much important as it determines the intrinsic grouping among the unlabeled data present. There are no criteria for a good clustering. It depends on the user, what is the criteria they may use which satisfy their need.
- Divided into two subgroups :
    > Hard Clustering: In hard clustering, each data point either belongs to a cluster completely or not. 

    > Soft Clustering: In soft clustering, instead of putting each data point into a separate cluster, a probability or likelihood of that data point to be in those clusters is assigned. 
- Clustering Methods :

       1. Density-Based Methods
       2. Hierarchical Based Methods 
       3. Partitioning Methods
       4. Grid-based Methods

- Clustering Algorithms :

> K-means clustering algorithm : It is the simplest unsupervised learning algorithm that solves clustering problem. K-means algorithm partition n observations into k clusters where each observation belongs to the cluster with the nearest mean serving as a prototype of the cluster .
     
      1. Specify the desired number of clusters K
      2. Randomly assign each data point to a cluster 
      3. Compute cluster centroids 
      4. Re-compute cluster centroids 
      5. Repeat steps 4 and 5 until no improvements are possible

**Comment by ucrayca** [comment]
CLASSIFICATION
- Supervised learning method
- The problem of identifying to which of a set of categories (sub-populations) a new observation belongs, on the basis of a training set of data containing observations (or instances) whose category membership is known.
- Types of Classification Algorithms:

1. Linear Models

- Logistic Regression
- Support Vector Machines

2. Nonlinear models

- K-nearest Neighbors (KNN)
- Kernel Support Vector Machines (SVM)
- Naïve Bayes
- Decision Tree Classification
- Random Forest Classification

**Naive Bayes**
Naive Bayes is a probabilistic classifier in Machine Learning which is built on the principle of Bayes theorem. Naive Bayes classifier makes an assumption that one particular feature in a class is unrelated to any other feature and that is why it is known as naive.

**Decision Tree**
Decision tree, as the name states, is a tree-based classifier in Machine Learning. You can consider it to be an upside-down tree, where each node splits into its children based on a condition. 

**Logistic Regression**
Logistic regression is a binary classification algorithm which gives out the probability for something to be true or false.

**Support Vector Machine (SVM)**
- SVMs are classification algorithms used to assign data to various classes.
- They involve detecting hyperplanes which segregate data into classes.
- SVMs are very versatile and are also capable of performing linear or nonlinear classification, regression, and outlier detection.
- Once ideal hyperplanes are discovered, new data points can be easily classified.
- The optimization objective is to find “maximum margin hyperplane” that is farthest from the closest points in the two classes (these points are called support vectors).
